# Generated by Django 2.1.7 on 2019-02-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number',
        ),
    ]
