# Generated by Django 2.1.7 on 2019-03-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190218_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
    ]
